version: '3.8'

services:
  whtzup-app:
    build: .
    container_name: whtzup-event-app
    ports:
      - "7777:7777"
    volumes:
      # Persist events data
      - ./data:/app/data
      # Mount events file for easy updates
      - ./public/events-user.json:/app/public/events-user.json
      # Mount backups directory
      - ./backups:/app/backups
    environment:
      - NODE_ENV=production
      - PORT=7777
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:7777/api/events', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whtzup-network

  # Optional: Nominatim geocoding service
  nominatim:
    image: mediagis/nominatim:4.2
    container_name: whtzup-nominatim
    ports:
      - "7070:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/estonia-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/estonia-updates/
      - IMPORT_WIKIPEDIA=false
      - IMPORT_US_POSTCODES=false
      - NOMINATIM_PASSWORD=your_password_here
    volumes:
      - nominatim_data:/var/lib/postgresql/14/main
      - nominatim_import:/nominatim/import
    restart: unless-stopped
    networks:
      - whtzup-network
    profiles:
      - geocoding

networks:
  whtzup-network:
    driver: bridge

volumes:
  nominatim_data:
  nominatim_import:

