version: '3.8'

services:
  # Main application
  whtzup-app:
    build: .
    container_name: whtzup-event-app
    environment:
      - NODE_ENV=production
      - PORT=7777
    volumes:
      - ./data:/app/data
      - ./public/events-user.json:/app/public/events-user.json
      - ./backups:/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:7777/api/events', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal
    expose:
      - "7777"

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: whtzup-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - whtzup-app
    restart: unless-stopped
    networks:
      - internal
      - external

  # Optional: Redis for caching (if needed in future)
  redis:
    image: redis:7-alpine
    container_name: whtzup-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - internal
    profiles:
      - cache

  # Optional: Nominatim geocoding service
  nominatim:
    image: mediagis/nominatim:4.2
    container_name: whtzup-nominatim
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/estonia-latest.osm.pbf
      - REPLICATION_URL=https://download.geofabrik.de/europe/estonia-updates/
      - IMPORT_WIKIPEDIA=false
      - IMPORT_US_POSTCODES=false
      - NOMINATIM_PASSWORD=your_secure_password_here
    volumes:
      - nominatim_data:/var/lib/postgresql/14/main
      - nominatim_import:/nominatim/import
    restart: unless-stopped
    networks:
      - internal
    profiles:
      - geocoding

networks:
  internal:
    internal: true
  external:
    driver: bridge

volumes:
  nginx_logs:
  redis_data:
  nominatim_data:
  nominatim_import:

