# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and archive the app"
  lane :build_archive do
    # Increment build number manually
    increment_build_number(
      xcodeproj: "EventDiscovery.xcodeproj"
    )
    
    # Clean build artifacts
    clean_build_artifacts
    
    # Build the app
    build_app(
      scheme: "EventDiscovery",
      export_method: "app-store",
      export_options: {
        method: "app-store"
      },
      clean: true,
      skip_archive: false,
      output_directory: ".",
      output_name: "EventDiscovery.ipa"
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    # Switch to build_archive lane
    build_archive
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      app_identifier: "com.eventdiscovery.app"
    )
  end

  desc "Build for simulator"
  lane :build_simulator do
    # Clean build artifacts
    clean_build_artifacts
    
    # Build for simulator
    build_app(
      scheme: "EventDiscovery",
      configuration: "Debug",
      destination: "generic/platform=iOS Simulator",
      clean: true
    )
  end
end
