name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
        port: ${{ secrets.DIGITAL_OCEAN_PORT }}
        script: |
          cd /opt/whtzup-app
          git pull origin main
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d --build
          echo "Deployment completed successfully!"
          
    - name: Health check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
        port: ${{ secrets.DIGITAL_OCEAN_PORT }}
        script: |
          sleep 30
          curl -f http://localhost:4000/api/health || exit 1
          echo "Health check passed!"
